name: Docker

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: build the image
      run: docker build -t ghcr.io/${{github.repository}}:${{github.ref_name}} .

    - name: list images
      run: docker image ls

    - name: push the image
      if: github.ref_type == 'tag'
      run: |
        docker login ghcr.io -u ${{github.actor}} --password-stdin <<< "${{secrets.GITHUB_TOKEN}}"
        docker push ghcr.io/${{github.repository}}:${{github.ref_name}}
