name: Docker

on:
  push:
    #branches:
    #- '*'
    tags:
    - '*'
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_ENABLED: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
      PUSH_LATEST: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build images
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository }}:latest
        #push: true

    - name: Login to Docker Hub
      if: ${{ env.DOCKERHUB_ENABLED == true }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    #- name: push the image
    #  if: github.ref_type == 'tag'
    #  run: |
    #    docker login ghcr.io -u ${{github.actor}} --password-stdin <<< "${{secrets.GITHUB_TOKEN}}"
    #    docker tag ghcr.io/${{github.repository}}:latest ghcr.io/${{github.repository}}:${{github.ref_name}}
    #    docker push ghcr.io/${{github.repository}}:${{github.ref_name}}
