name: Docker

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-24.04
    env:
      DOCKERHUB_REPOSITORY: koron/webgentools

      DOCKERHUB_ENABLED: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
      PUSH_LATEST: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
      PUSH_TAG: ${{ github.ref_type == 'tag' }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository }}:latest
        push: ${{ env.PUSH_LATEST }}

    - name: Push a tag
      if: env.PUSH_TAG == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        push: true

    - name: Login to Docker Hub
      if: env.DOCKERHUB_ENABLED == 'true' && (env.PUSH_LATEST == 'true' || env.PUSH_TAG == 'true')
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push latest to Docker Hub
      if: env.DOCKERHUB_ENABLED == 'true' && env.DOCKERHUB_REPOSITORY != '' && env.PUSH_LATEST == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.DOCKERHUB_REPOSITORY }}:latest
        push: true

    - name: Push a tag to Docker Hub
      if: env.DOCKERHUB_ENABLED == 'true' && env.DOCKERHUB_REPOSITORY != '' && env.PUSH_TAG == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.DOCKERHUB_REPOSITORY }}:${{ github.ref_name }}
        push: true
